# Test config with multiple timeframes
data:
  symbol: BTCUSDT
  market_type: future

binance:
  base_url: "https://api.binance.com"
  
pairs:
  - BTCUSDT

timeframes:
  - 5m
  - 1h
  - 4h

months: 1
force_full_rebuild: true
retain_full_history: false

bb_periods: [24]
bb_devs: [2.0]
ma_periods: [4]
enable_ma_features: true

target:
  horizon: 20
  sideways_threshold_pct: 1.0
  adaptive_thresholds:
    enabled: true
    base_timeframe: "1h"
    multipliers:
      "5m": 0.3
      "1h": 1.0
      "4h": 2.0

external:
  enable_coingecko: false
  enable_coinmetrics: false
  enable_dune: false

multi_horizon:
  horizons: [5, 20]
  enable_extremes: false

output:
  sqlite_db: data/test_db/preprocessed.sqlite